### ISSUE TITLE
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.... (While switching to another tab in curved navigation bar)

### ISSUE THREAD

**Issue by Ashbuhrz** [ponnamkarthik/FlutterToast#194]
E/flutter ( 4123): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter ( 4123): At this point the state of the widget's element tree is no longer stable.
E/flutter ( 4123): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter ( 4123): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3785:9)
E/flutter ( 4123): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3799:6)
E/flutter ( 4123): #2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3918:12)
E/flutter ( 4123): #3      Overlay.of (package:flutter/src/widgets/overlay.dart:256:19)
E/flutter ( 4123): #4      FlutterToast._showOverlay (package:fluttertoast/fluttertoast.dart:58:13)
E/flutter ( 4123): #5      FlutterToast.removeCustomToast (package:fluttertoast/fluttertoast.dart:69:5)
E/flutter ( 4123): #6      FlutterToast._showOverlay.<anonymous closure> (package:fluttertoast/fluttertoast.dart:61:7)
E/flutter ( 4123): #7      _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 4123): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4123): #9      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 4123): #10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 4123): #11     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 4123): #12     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 4123): #13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 4123): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 4123): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 4123): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 4123): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by palcodes** [comment]
I am getting this same error. Any way around to solve this?
I have a bottom navigation bar and it doesn't kill the screens.

**Comment by palcodes** [comment]
Sorry for not writing a better explanation of the problem I am facing.
The app that I am building basically has a bottom navigation bar which helps you navigate along 5 main screens.
So my purpose was to keep them all stacked and show the one clicked on the top, so as to keep all the 5 screens in memory when running the app, and I guessed that one of the reasons behind this error could be improper handling of state widget tree.
> I couldn't get to a solution for this package, might look into it in the future, and open up a PR. But for now, I am just creating a custom widget that behaves in a similar way.

**Comment by ponnamkarthik** [comment]
You can create a global key 

```dart
static final GlobalKey<NavigatorState> navigatorKey = new GlobalKey<NavigatorState>();
```

then assign it to 

```dart
return MaterialApp(
      navigatorKey: NavigationService.navigatorKey,
...
```

then pass 

```dart
navigatorKey.currentContext
```

to initialize the FToast

**Comment by VCasecnikovs** [comment]
The solution is not working...

**Comment by VCasecnikovs** [comment]
Problem is  - overlay is under MaterialApp, so it can not get Overlay.of(context)

**Comment by robertoltrocha** [comment]
same issue

**Comment by AlexSeednov** [comment]
Hey! Maybe it's too late, but it can be useful for other developers.

To prevent throwing exception I prepared PR with safer work. But it also didn't show FToast if context will be unmuted.

To get possibility to show context after screen popped (and given context unmuted) you can use Context from Navigator key as @ponnamkarthik told earlier. But in this case you also need to add overlay entry manually as I told here - https://github.com/ponnamkarthik/FlutterToast/issues/393#issuecomment-1423684027

Best regards, Alex
