### ISSUE TITLE
NullPointerException: FToast(context).showToast() without toastDuration

### ISSUE THREAD

**Issue by shemhazai** [ponnamkarthik/FlutterToast#220]
toastDuration in the FToast(context).showToast() is not required, however lack of this property causes errors.
We can see that the library tries to provide default duration in some places however it's not a complete solution.

## Mentioned implementation:
```
  void showToast({
    @required Widget child,
    Duration toastDuration,
    ToastGravity gravity,
  }) {
    OverlayEntry newEntry = OverlayEntry(builder: (context) {
      return _getPostionWidgetBasedOnGravity(child, gravity, toastDuration);
    });
    _overlayQueue.add(_ToastEntry(entry: newEntry, duration: toastDuration ?? Duration(seconds: 2)));
    if (_timer == null) _showOverlay();
  }
```

## Exception thrown:
```
I/flutter (28186): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28186): The following NoSuchMethodError was thrown building Positioned(top: 100.0, right: 24.0):
I/flutter (28186): The getter 'inMilliseconds' was called on null.
I/flutter (28186): Receiver: null
I/flutter (28186): Tried calling: inMilliseconds
I/flutter (28186): 
I/flutter (28186): The relevant error-causing widget was:
I/flutter (28186):   MaterialApp file:///Users/shemhazai/Projects/schoolpen/lib/main_app.dart:48:14
I/flutter (28186): 
I/flutter (28186): When the exception was thrown, this was the stack:
I/flutter (28186): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (28186): #6      ToastStateFulState.initState (package:fluttertoast/fluttertoast.dart:209:12)
I/flutter (28186): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
I/flutter (28186): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
I/flutter (28186): ...     Normal element mounting (27 frames)
I/flutter (28186): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
I/flutter (28186): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
I/flutter (28186): #37     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5624:32)
I/flutter (28186): #38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
I/flutter (28186): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
I/flutter (28186): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
I/flutter (28186): #41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
I/flutter (28186): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
I/flutter (28186): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
I/flutter (28186): #44     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
I/flutter (28186): #45     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (28186): #46     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (28186): #47     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
I/flutter (28186): #48     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
I/flutter (28186): #52     _invoke (dart:ui/hooks.dart:253:10)
I/flutter (28186): #53     _drawFrame (dart:ui/hooks.dart:211:3)
I/flutter (28186): (elided 8 frames from dart:async and dart:async-patch)
```

**Comment by ponnamkarthik** [comment]
Fixed in `7.1.0`
