### ISSUE TITLE
SyntaxError: Unexpected identifier at HTMLHeadElement.[dartx.append] 

### ISSUE THREAD

**Issue by hiashutoshsingh** [ponnamkarthik/FlutterToast#233]
SyntaxError: Unexpected identifier
    at HTMLHeadElement.[dartx.append] (http://localhost:53733/dart_sdk.js:63634:31)
    at html$._ChildrenElementList._wrap.add (http://localhost:53733/dart_sdk.js:80891:32)
    at fluttertoast_web.FluttertoastWebPlugin.new.addHtmlToast (http://localhost:53733/packages/fluttertoast/fluttertoast_web.dart.lib.js:124:50)
    at fluttertoast_web.FluttertoastWebPlugin.new.showToast (http://localhost:53733/packages/fluttertoast/fluttertoast_web.dart.lib.js:80:12)
    at fluttertoast_web.FluttertoastWebPlugin.new.handleMethodCall (http://localhost:53733/packages/fluttertoast/fluttertoast_web.dart.lib.js:59:18)
    at handleMethodCall.next (<anonymous>)

**Comment by hiashutoshsingh** [comment]
this error is shown when i use text like` I can't do` 't is giving error somehow it was working before, i din't changed package version or flutter version.

**Comment by pmrajani** [comment]
SyntaxError: Unexpected identifier
    at HTMLHeadElement.[dartx.append] (http://localhost:64787/dart_sdk.js:64006:31)
    at html$._ChildrenElementList._wrap.add (http://localhost:64787/dart_sdk.js:81287:32)
    at fluttertoast_web.FluttertoastWebPlugin.new.addHtmlToast (http://localhost:64787/packages/fluttertoast/fluttertoast_web.dart.lib.js:127:50)
    at fluttertoast_web.FluttertoastWebPlugin.new.showToast (http://localhost:64787/packages/fluttertoast/fluttertoast_web.dart.lib.js:83:12)
    at fluttertoast_web.FluttertoastWebPlugin.new.handleMethodCall (http://localhost:64787/packages/fluttertoast/fluttertoast_web.dart.lib.js:61:18)
    at handleMethodCall.next (<anonymous>)

**Comment by pmrajani** [comment]
Same error beta chhanel

**Comment by hiashutoshsingh** [comment]
and this is the error which is coming from 3-4 days it was not happening before @pmrajani
