### ISSUE TITLE
toast doesn't take context from getit

### ISSUE THREAD

**Issue by hiashutoshsingh** [ponnamkarthik/FlutterToast#234]
GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
  navigatorKey.currentContext;

this context doesn't work to show toast, it is throwing error in showing overlay.

```
TypeError: Cannot read property 'insert' of null
    at fluttertoast.FToast._internal.[_showOverlay] (http://localhost:53491/packages/fluttertoast/fluttertoast.dart.lib.js:1019:39)
    at fluttertoast.FToast._internal.showToast (http://localhost:53491/packages/fluttertoast/fluttertoast.dart.lib.js:1055:51)
    at Function.displaySnackBar (http://localhost:53491/packages/services/web/general_details.dart.lib.js:194826:16)
    at http://localhost:53491/packages/services/web/general_details.dart.lib.js:153051:25
    at _RootZone.runUnary (http://localhost:53491/dart_sdk.js:37029:58)
    at _FutureListener.catchError.handleError (http://localhost:53491/dart_sdk.js:32130:48)
    at handleError (http://localhost:53491/dart_sdk.js:32679:51)
```

**Comment by phijma** [comment]
Can you show more code? (Where do you create this navigatorKey?)

**Comment by ponnamkarthik** [comment]
we cannot use natvigatorKey context as its on very top of the widget tree we cannot insert an every with that context


try this 

```dart

GlobalKey navigatorKey = GlobalKey();

//...

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(
        title: Text("Toast"),
      ),
//...
//...

fToast.init(navigatorKey.currentState.context);

```
