### ISSUE TITLE
Exception with targetSdkVersion 30

### ISSUE THREAD

**Issue by jonbhanson** [ponnamkarthik/FlutterToast#255]
Thanks for a great widget!

I'm running into a problem when I change the `targetSdkVersion` from `29` to `30` in `android/app/build.gradle`.  This simple app will demonstrate the problem:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text('Show Toast'),
            onPressed: () => Fluttertoast.showToast(msg: "This is a toast message."),
          ),
        ),
      ),
    );
  }
}
```

This is the error that is generated:

```
kotlin.KotlinNullPointerException
	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:66)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by ponnamkarthik** [comment]
Fixed `7.1.5` please check
