### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by Johann673** [ponnamkarthik/FlutterToast#261]
Hi,

I use this library and work perfectly when i test on emulator and real phone (OnePlus). 
But, on some samsung phone, the toast don't appear and i have an exception, tested and reproduce on Samsung M31 and Samsung S20.

I just use fluttertoast like this : `Fluttertoast.showToast(msg: "Message");`

I have this exception : 

```
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): Failed to handle method call
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): kotlin.KotlinNullPointerException
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:66)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:693)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at android.os.Looper.loop(Looper.java:206)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at android.app.ActivityThread.main(ActivityThread.java:8414)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
E/MethodChannel#PonnamKarthik/fluttertoast( 8036): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter ( 8036): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, null, null, kotlin.KotlinNullPointerException
E/flutter ( 8036): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:66)
E/flutter ( 8036): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter ( 8036): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 8036): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:693)
E/flutter ( 8036): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8036): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 8036): 	at android.os.Looper.loop(Looper.java:206)
E/flutter ( 8036): 	at android.app.ActivityThread.main(ActivityThread.java:8414)
E/flutter ( 8036): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8036): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
E/flutter ( 8036): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/flutter ( 8036): )
E/flutter ( 8036): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter ( 8036): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 8036): <asynchronous suspension>
E/flutter ( 8036): #2      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:78:16)
```

I'm on the last version, 7.1.6, also tested on 7.1.5.

**Comment by jil8885** [comment]
I works on flutter 1.22.4 but I got same problem on 1.22.5, I think it's better to use previous flutter instead

**Comment by ponnamkarthik** [comment]
@Johann673 @jil8885 i think you both are running in android 11 - will be fixed in new version
