### ISSUE TITLE
 MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)

### ISSUE THREAD

**Issue by JaCoxxx** [ponnamkarthik/FlutterToast#276]
```
E/flutter ( 5187): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
E/flutter ( 5187): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 5187): <asynchronous suspension>
E/flutter ( 5187): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 5187): #2      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:78:31)
E/flutter ( 5187): #3      Util.toast (package:fotile_ltc_app/util/utils.dart:37:25)
E/flutter ( 5187): #4      _DynamicAttachmentListState.downloadCallback (package:fotile_ltc_app/common/widget/dynamic_attachment_list.dart:114:10)
E/flutter ( 5187): #5      callbackDispatcher.<anonymous closure> (package:flutter_downloader/src/callback_dispatcher.dart:24:13)
E/flutter ( 5187): #6      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
E/flutter ( 5187): #7      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:34)
E/flutter ( 5187): #8      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:283:33)
E/flutter ( 5187): #9      _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter ( 5187): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 5187): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5187): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5187): #13     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter ( 5187): #14     _dispatchPlatformMessage (dart:ui/hooks.dart:154:5)
E/flutter ( 5187): 
```

`flutter doctor`
```
E:\web-flutter\project_business_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.18363.1379], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

```
E:\web-flutter\project_business_flutter>flutter --version
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (4 months ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3

```

**Comment by muyuanqiang7** [comment]
i have the same problem in ios, i do not test on android ,i havd sloved the problem by rm ios/Podfile.lock and run pod install

**Comment by XuanTung95** [comment]
Hot reload won't work for the first time install the library. Try to close and re-run the app may fix the issue.
