### ISSUE TITLE
Error: null check operator used on a null value

### ISSUE THREAD

**Issue by proninyaroslav** [ponnamkarthik/FlutterToast#338]
**OS:** Linux
**Flutter Version:** 2.2.3
**Package version:** 8.0.8

This happened when I showed the same toast twice and closed the modal window (AlertDialog):
```
Null check operator used on a null value
#0      FToast._showOverlay (package:fluttertoast/fluttertoast.dart:148)
#1      FToast.removeCustomToast (package:fluttertoast/fluttertoast.dart:164)
#2      FToast._showOverlay.<anonymous closure>.<anonymous closure> (package:fluttertoast/fluttertoast.dart:152)
#3      new Future.delayed.<anonymous closure> (dart:async/future.dart:315)
#4      _rootRun (dart:async/zone.dart:1346)
#5      _CustomZone.run (dart:async/zone.dart:1258)
#6      _CustomZone.runGuarded (dart:async/zone.dart:1162)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202)
#8      _rootRun (dart:async/zone.dart:1354)
#9      _CustomZone.run (dart:async/zone.dart:1258)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186)
#11     TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:407)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

Example:
```Dart
Toast.of(context).show(text: 'Text');
```

**Comment by shadabunique** [comment]
Fixed in PR https://github.com/ponnamkarthik/FlutterToast/pull/346

**Comment by pheromone** [comment]
Or was it unsuccessful?
Flutter Version: 2.2.3
Package version: 8.0.8
```
  late FToast fToast;
....
  @override
  void initState() {
    super.initState();

    BuildContext context = navigatorKey.currentState!.context;

    fToast = FToast();
    fToast.init(context);
  }
...
 fToast.showToast(
        child: toast,
        gravity: ToastGravity.CENTER,
        toastDuration: Duration(seconds: 2),
      );
```
