### ISSUE TITLE
PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null)

### ISSUE THREAD

**Issue by eugenio-tesio** [PonnamKarthik/FlutterToast#35]
The error:

```
E/flutter (17884): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (17884): PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null)
E/flutter (17884): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (17884): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (17884): <asynchronous suspension>
E/flutter (17884): #2      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:45:33)
E/flutter (17884): <asynchronous suspension>
E/flutter (17884): #3      Helper.showToast (package:consumos_app/utils/helper.dart:199:18)
E/flutter (17884): #4      _ConsumosPageState.getConsumos.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:consumos_app/consumos.dart:66:30)
E/flutter (17884): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (17884): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (17884): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (17884): #8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
E/flutter (17884): #9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter (17884): #10     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
E/flutter (17884): #11     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
E/flutter (17884): #12     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
E/flutter (17884): #13     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
E/flutter (17884): #14     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
E/flutter (17884): #15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
E/flutter (17884): #16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (17884): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (17884): #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter (17884): #19     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter (17884): #20     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
E/flutter (17884): #21     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter (17884): #22     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
E/flutter (17884): #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (17884): #24     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (17884): #25     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (17884): #26     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (17884): #27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (17884): #28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

Flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [VersiÃ³n 10.0.17134.407], locale es-AR)
> [√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
> [√] Android Studio (version 3.1)
> [√] IntelliJ IDEA Ultimate Edition (version 2018.1)
> [√] VS Code (version 1.26.1)
> [√] VS Code, 64-bit edition (version 1.28.2)
> [√] Connected device (1 available)
> 
> • No issues found!

The flutter call:

```
Fluttertoast.showToast(
        msg: message,
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.BOTTOM,
        timeInSecForIos: 1,
        backgroundColor: Colors.black45,
        textColor: Colors.white
    );
```

If i remove backgroundColor: Colors.black45, textColor: Colors.white, it works fine.

**Comment by eugenio-tesio** [comment]
Maybe the error is in this code:

if (call.method.equals("showToast")) {
      String msg  = call.argument("msg").toString();
      String length = call.argument("length").toString();
      String gravity = call.argument("gravity").toString();
      **Long bgcolor = call.argument("bgcolor");
      Long textcolor = call.argument("textcolor");**
...
