### ISSUE TITLE
Add Desktop Support (MacOS, Windows and Linux)

### ISSUE THREAD

**Issue by ttzein6** [ponnamkarthik/FlutterToast#491]

**Comment by allComputableThings** [comment]
+1 When I try to show a toast, I get:
```
Syncing files to device Linux...
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:100:17)
<asynchronous suspension>
```
