### ISSUE TITLE
No implementation found for method showToast on channel PonnamKarthik/fluttertoast

### ISSUE THREAD

**Issue by trinhminhhieu** [ponnamkarthik/FlutterToast#510]
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method showToast on channel PonnamKarthik/fluttertoast)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      Fluttertoast.showToast (package:fluttertoast/fluttertoast.dart:100:17)
<asynchronous suspension>

**Comment by ponnamkarthik** [comment]
Can you please try 

```
flutter clean
```

then try to run again

**Comment by pooransuthar** [comment]
> Can you please try
> 
> ```
> flutter clean
> ```
> 
> then try to run again

Thank you! worked for me.

**Comment by teolex** [comment]
I'm using fluttertoast: ^8.2.10.
flutter clean didn't work for me...(ㅠ_ㅠ)

`version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.4
  provider: ^6.0.0
  fluttertoast: ^8.2.10
`

**Comment by EArminjon** [comment]
See solution here : https://github.com/ponnamkarthik/FlutterToast/issues/553
