### ISSUE TITLE
Error: A value of type 'JSString' can't be assigned to a variable of type 'String'.

### ISSUE THREAD

**Issue by kjxbyz** [ponnamkarthik/FlutterToast#528]
flutter: 3.24.0
fluttertoast: 8.2.7

```
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../.pub-cache/hosted/pub.dev/fluttertoast-8.2.7/lib/fluttertoast_web.dart:128:29:
Error: A value of type 'JSString' can't be assigned to a variable of type 'String'.
      ..innerHTML = content.toJS;
                            ^
Error: Compilation failed.
  Command: /vercel/path0/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /vercel/path0/flutter/bin/cache/dart-sdk/bin/snapshots/dart2js.dart.snapshot --platform-binaries=/vercel/path0/flutter/bin/cache/flutter_web_sdk/kernel --invoker=flutter_tool -Ddart.vm.product=true -DSENTRY_DSN=https://103b9cef7b4baae533f463ad4629ead2@o4507226640285696.ingest.us.sentry.io/4507226644021248 -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=true -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/b8800d88be4866db1b15f8b954ab2573bba9960f/ --native-null-assertions --no-source-maps -o /vercel/path0/.dart_tool/flutter_build/5596641d13f7911ce03b680b6e614832/app.dill --packages=.dart_tool/package_config.json --cfe-only /vercel/path0/.dart_tool/flutter_build/5596641d13f7911ce03b680b6e614832/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:122:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:370:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:203:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:534:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:635:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:227:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>
Compiling lib/main.dart for the Web...                             20.7s
Error: Failed to compile application for the Web.
```

**Comment by tushar-asodariya** [comment]
I am also facing same issue on 3.19.6, with 8.2.7

**Comment by cdp6411** [comment]
import 'package:fluttertoast/fluttertoast.dart';
class AppDialogs {
  static showTextError(String errorText) {
    Fluttertoast.showToast(
      msg: errorText,
      toastLength: Toast.LENGTH_LONG,
      gravity: ToastGravity.CENTER,
 timeInSecForIosWeb: 2,
      backgroundColor: Colors.red,
      textColor: Colors.white,
      fontSize: 16.0,
    );
  }
}
![Screenshot 2024-08-14 at 6 45 53 PM](https://github.com/user-attachments/assets/956e2b0d-8522-4b0e-b285-df69e8b7aae6
![Screenshot 2024-08-14 at 6 46 18 PM](https://github.com/user-attachments/assets/00ba3a27-6906-42f8-a527-5cba550a85aa)
)

@ponnamkarthik Can you please look into this.

**Comment by ponnamkarthik** [comment]
@cdp6411 also send the sample errorText you are using

**Comment by cdp6411** [comment]
@ponnamkarthik Here is the Text ---> 'Your reply was saved! Thank you!'

**Comment by cdp6411** [comment]
@ponnamkarthik I have added toString and it works. ![image](https://github.com/user-attachments/assets/ab3b53db-94c6-411d-b6ca-0937f3c869f1)

**Comment by tushar-asodariya** [comment]
> Hello @tushar-asodariya i tested on flutter version 3.24.0 i did tested builing the example app for web and it build perfectly without .toString()
> 
> can you please provide the code to reproduce the issue


![Uploading Screenshot 2024-08-14 at 18.57.52.png…]()

**Comment by ponnamkarthik** [comment]
updated please check with version 8.2.8
