### ISSUE TITLE
 java.lang.Exception: denglibo Toast callstack! strTip=我是Toast

### ISSUE THREAD

**Issue by lblblong** [PonnamKarthik/FlutterToast#80]
In the Android environment will generate an exception
```
W/System.err( 3615): java.lang.Exception: denglibo Toast callstack! strTip=我是Toast
W/System.err( 3615): 	at android.widget.Toast.show(Toast.java:127)
W/System.err( 3615): 	at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.kt:92)
W/System.err( 3615): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err( 3615): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
W/System.err( 3615): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
W/System.err( 3615): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 3615): 	at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 3615): 	at android.os.Looper.loop(Looper.java:122)
W/System.err( 3615): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 3615): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3615): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3615): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err( 3615): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
E/EGL_adreno( 3615): tid 3642: eglSurfaceAttrib(1266): error 0x3009 (EGL_BAD_MATCH)
W/OpenGLRenderer( 3615): Failed to set EGL_SWAP_BEHAVIOR on surface 0x9fed12e0, error=EGL_BAD_MATCH
D/EGL_adreno( 3615): eglMakeCurrent: 0xb3ee3040: ver 3 1 (tinfo 0x9fff35d0)
E/MediaPlayer( 3615): Should have subtitle controller already set
D/EGL_adreno( 3615): eglMakeCurrent: 0xb3ee3040: ver 3 1 (tinfo 0x9fff35d0)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.16299.431], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.32.2)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (1 available)

! Doctor found issues in 3 categories.
```

**Comment by lifetin** [comment]
和我一样啊
https://github.com/PonnamKarthik/FlutterToast/issues/87

**Comment by WinnieX** [comment]
一样的错误：
W/System.err( 2586): java.lang.Exception: denglibo Toast callstack! strTip=下载完成
W/System.err( 2586): 	at android.widget.Toast.show(Toast.java:127)
W/System.err( 2586): 	at io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.onMethodCall(FluttertoastPlugin.java:125)
W/System.err( 2586): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err( 2586): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
W/System.err( 2586): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
W/System.err( 2586): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 2586): 	at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 2586): 	at android.os.Looper.loop(Looper.java:122)
W/System.err( 2586): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 2586): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2586): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 2586): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
W/System.err( 2586): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
